# Generated by Django 4.2.2 on 2023-12-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab_app", "0003_patient_last_name_alter_file_user_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={"verbose_name_plural": "Files Entries"},
        ),
        migrations.AddField(
            model_name="file",
            name="slug",
            field=models.SlugField(blank=True, default=""),
        ),
    ]
