# Generated by Django 4.2.2 on 2023-12-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lab_app", "0005_alter_file_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={"verbose_name_plural": "Patient Entries"},
        ),
    ]
