# Generated by Django 4.2.2 on 2023-12-17 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lab_app", "0007_remove_file_slug_patient_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="files",
                to="lab_app.patient",
            ),
        ),
    ]
