# Generated by Django 4.2.2 on 2023-12-17 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lab_app", "0008_alter_file_patient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="patient",
        ),
        migrations.AddField(
            model_name="patient",
            name="file",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="lab_app.file",
            ),
        ),
    ]
