# Generated by Django 4.2.2 on 2023-12-21 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lab_app", "0009_remove_file_patient_patient_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="file",
        ),
        migrations.AddField(
            model_name="file",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="lab_app.patient",
            ),
        ),
    ]
