# Generated by Django 4.2.2 on 2023-12-27 02:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab_app", "0010_remove_patient_file_file_patient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="user_name",
        ),
        migrations.AddField(
            model_name="file",
            name="date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="address",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="age",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="full_name",
            field=models.DateField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="p_number",
            field=models.CharField(
                blank=True,
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="s_number",
            field=models.CharField(
                blank=True,
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
    ]
