# Generated by Django 4.2.2 on 2023-12-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab_app", "0011_remove_patient_last_name_remove_patient_user_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="full_name",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
