# Generated by Django 5.0 on 2023-12-27 23:18

import phone_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lab_app", "0012_alter_patient_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="p_number",
            field=phone_field.models.PhoneField(
                blank=True, help_text="Contact phone number", max_length=31
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="s_number",
            field=phone_field.models.PhoneField(
                blank=True, help_text="Contact phone number", max_length=31
            ),
        ),
    ]
